const {test}=require('node:test');
const assert=require('node:assert/strict');
const M=require('../src/karaoke_generator/static/manual-model.js');
function fixture(){return {project_id:'song',revision:0,duration:30,roles:[{id:'r1',name:'Lead',color:'#b3a6ed'},{id:'r2',name:'Echo',color:'#80c4b0'}],annotations:[{annotation_id:'a1',occurrence_id:'o1',unit:'part',text:'hel',start:2,end:3,role_id:'r1',source_word_id:'w1'},{annotation_id:'a2',occurrence_id:'o1',unit:'part',text:'lo',start:3,end:4,role_id:'r1',source_word_id:'w1'},{annotation_id:'a3',occurrence_id:'o2',unit:'word',text:'hello',start:3,end:4.5,role_id:'r2',source_word_id:'w1'},{annotation_id:'target',occurrence_id:'target-o',unit:'word',text:'hello',start:10,end:11,role_id:null}],occurrences:[{occurrence_id:'o1',annotation_ids:['a1','a2'],complete:true,source_word_id:'w1'},{occurrence_id:'o2',annotation_ids:['a3'],complete:true,source_word_id:'w1'},{occurrence_id:'target-o',annotation_ids:['target'],complete:true}],reviews:[{review_id:'review',start:1,end:5,all_roles:true,uncertainties:[]},{review_id:'silence',start:20,end:25,all_roles:true,uncertainties:[]}]};}
test('time field contracts preserve the opposite boundary and reject the entire invalid operation',()=>{const p=fixture(),original=JSON.stringify(p);let n=M.edit(p,['a1'],'start',2.25);assert.deepEqual([n.annotations[0].start,n.annotations[0].end],[2.25,3]);n=M.edit(p,['a1'],'end',3.5);assert.deepEqual([n.annotations[0].start,n.annotations[0].end],[2,3.5]);n=M.edit(p,['a1'],'duration',2.75);assert.deepEqual([n.annotations[0].start,n.annotations[0].end],[2,4.75]);for(const args of [['start',3],['end',1],['duration',40]])assert.throws(()=>M.edit(p,['a1'],...args));assert.equal(JSON.stringify(p),original);assert.throws(()=>M.edit(p,['a1','a2'],'start',2));});
test('a group clamps as a unit, preserves offsets, durations and roles at both recording edges',()=>{const p=fixture(),ids=['a1','a2','a3'];let n=M.move(p,ids,-10);assert.deepEqual(n.annotations.slice(0,3).map(a=>[a.start,a.end,a.role_id]),[[0,1,'r1'],[1,2,'r1'],[1,2.5,'r2']]);n=M.move(p,ids,100);assert.deepEqual(n.annotations.slice(0,3).map(a=>[a.start,a.end]),[[27.5,28.5],[28.5,29.5],[28.5,30]]);assert.deepEqual(n.annotations[3],p.annotations[3]);});
test('repeated paste adds independent occurrences without modifying identical target content',()=>{const p=fixture(),clip=M.copy(p,['a1','a2','a3']),first=M.paste(p,clip,10),second=M.paste(first.project,clip,10);assert.equal(second.project.annotations.length,10);assert.deepEqual(second.project.annotations.slice(0,4),p.annotations);assert.equal(new Set(second.project.annotations.map(a=>a.annotation_id)).size,10);assert.equal(new Set(second.project.annotations.map(a=>a.occurrence_id)).size,7);assert.equal(first.project.occurrences.find(o=>o.occurrence_id===first.project.annotations[4].occurrence_id).complete,true);let changed=M.edit(second.project,['a1'],'text','ORIGINAL');assert.equal(changed.annotations[4].text,'hel');assert.equal(changed.annotations[7].text,'hel');assert.equal(changed.annotations[3].text,'hello');assert.notEqual(first.project.annotations[4].annotation_id,first.project.annotations[4].occurrence_id);});
test('partial-word copy stays incomplete, and whole-group overflow inserts nothing',()=>{const p=fixture(),clip=M.copy(p,['a2']),next=M.paste(p,clip,12).project,added=next.annotations.at(-1);assert.equal(next.occurrences.find(o=>o.occurrence_id===added.occurrence_id).complete,false);assert.equal(added.provenance.copied_from_annotation_id,'a2');assert.throws(()=>M.paste(p,M.copy(p,['a1','a3']),29),/ничего не вставлено/);assert.equal(p.annotations.length,4);});
test('deleting a part makes surviving occurrence incomplete; undo restores exact group and reviews',()=>{const h=new M.History(fixture()),original=M.clone(h.project);h.commit(M.remove(h.project,['a1','a3']));assert.equal(h.project.occurrences.find(o=>o.occurrence_id==='o1').complete,false);assert.equal(h.project.annotations.length,2);assert.equal(h.past.length,1);h.undo();assert.deepEqual(h.project,original);h.redo();assert.deepEqual(h.project.annotations.map(a=>a.annotation_id),['a2','target']);});
test('role CRUD and group assignment preserve timing, undo includes role deletion',()=>{const p=fixture();let n=M.role(p,'add',{name:'Third',color:'#d3b47e'}),rid=n.roles.at(-1).id;n=M.edit(n,['a1','a3'],'role_id',rid);assert.equal(n.annotations[0].role_id,rid);assert.equal(n.annotations[2].role_id,rid);const h=new M.History(n);h.commit(M.role(n,'remove',rid));assert.equal(h.project.annotations[0].role_id,null);assert.equal(h.project.annotations[2].role_id,null);assert.equal(h.project.annotations[0].start,2);h.undo();assert.equal(h.project.annotations[0].role_id,rid);});
test('semantic edits clear touched checks only; colors and names do not; copy does not import review',()=>{const p=fixture();let n=M.role(p,'update',{id:'r1',name:'Main',color:'#aaaaaa'});assert.deepEqual(n.reviews,p.reviews);n=M.edit(p,['a1'],'role_id','r2');assert.deepEqual(n.reviews.map(r=>r.review_id),['silence']);n=M.paste(p,M.copy(p,['a1']),21).project;assert.deepEqual(n.reviews.map(r=>r.review_id),['review']);assert.deepEqual(p.reviews.map(r=>r.review_id),['review','silence']);});
test('manual words may be absent from TXT; deleting everything stays intentionally empty',()=>{let p=fixture(),r=M.add(p,{text:'自由ное',start:8,end:9});assert.equal(r.project.annotations.at(-1).text,'自由ное');p=M.remove(r.project,r.project.annotations.map(a=>a.annotation_id));assert.deepEqual(p.annotations,[]);assert.deepEqual(p.occurrences,[]);});
test('overlaps including identical copies always have separate selectable layout rectangles',()=>{const p=fixture();p.annotations.push({...p.annotations[2],annotation_id:'echo2',occurrence_id:'echo2-o'});const layout=M.layout(p.annotations,{pps:30,grouped:true,roles:p.roles});assert.equal(layout.items.length,5);const same=layout.items.filter(i=>i.annotation.role_id==='r2');assert.notEqual(same[0].y,same[1].y);assert.equal(same[0].x,same[1].x);assert.equal(same[0].annotation.start,same[1].annotation.start);});
test('performance lookup shows all concurrent executions and can filter roles without data mutation',()=>{const p=fixture(),original=JSON.stringify(p);assert.equal(M.currentAndNext(p.annotations,3.2).current.length,2);const filtered=p.annotations.filter(a=>a.role_id==='r2');assert.deepEqual(M.currentAndNext(filtered,3.2).current.map(a=>a.annotation_id),['a3']);assert.deepEqual(M.currentAndNext([],3.2),{current:[],next:[]});assert.equal(JSON.stringify(p),original);});
test('undo after successful save uses newest server revision and marks draft dirty',()=>{const h=new M.History(fixture());h.commit(M.edit(h.project,['a1'],'text','changed'));h.savedAs({...h.project,revision:3,saved_at:'now'});assert.equal(h.dirty,false);h.undo();assert.equal(h.project.revision,3);assert.equal(h.project.annotations[0].text,'hel');assert.equal(h.dirty,true);h.redo();assert.equal(h.project.annotations[0].text,'changed');assert.equal(h.project.revision,3);});
test('moving fractional source times preserves duration and relative offsets, including clamp and no horizontal movement',()=>{const p=fixture();p.annotations[0].start=2.123456;p.annotations[0].end=3.987654;p.annotations[1].start=3.999991;p.annotations[1].end=4.234567;const before=M.clone(p);const moved=M.move(p,['a1','a2'],.1119);assert.equal(moved.annotations[0].start,2.235456);assert.ok(Math.abs((moved.annotations[0].end-moved.annotations[0].start)-(p.annotations[0].end-p.annotations[0].start))<1e-9);assert.ok(Math.abs((moved.annotations[1].start-moved.annotations[0].start)-(p.annotations[1].start-p.annotations[0].start))<1e-9);assert.deepEqual(M.move(p,['a1','a2'],0),before);const clamped=M.move(p,['a1','a2'],-10);assert.equal(clamped.annotations[0].start,0);assert.equal(clamped.annotations[0].end,1.864198);const pasted=M.paste(p,M.copy(p,['a1','a2']),10).project;assert.equal(pasted.annotations.at(-2).start,10);assert.equal(pasted.annotations.at(-2).end,11.864198);});

test('caption windows contain only complete advertised lanes and clamp when roles disappear',()=>{
  const annotations=Array.from({length:5},(_,index)=>({annotation_id:`row-${index}`,text:`row ${index}`,start:10,end:12,role_id:null}));
  const layout=M.layout(annotations,{pps:60}),original=JSON.stringify(annotations);
  for(const count of [2,3]){
    const first=M.captionWindow(layout,0,count),next=M.captionWindow(layout,first.first+1,count),last=M.captionWindow(layout,99,count);
    assert.deepEqual(first.items.map(item=>item.lane),Array.from({length:count},(_,i)=>i));
    assert.deepEqual(next.items.map(item=>item.lane),Array.from({length:count},(_,i)=>i+1));
    assert.equal(last.end,5);assert.equal(last.items.length,count);
  }
  assert.deepEqual(M.captionWindow(M.layout(annotations.slice(0,1)),3,2).items.map(item=>item.lane),[0]);
  assert.equal(JSON.stringify(annotations),original);
});
test('revealing a source time centers it in the usable timeline and clamps at recording edges',()=>{
  for(const [width,pps] of [[1280,60],[960,120]]){
    const scroll=M.scrollForTime(40,pps,width,100);
    assert.equal(74+40*pps-scroll,(width+74)/2);
    assert.equal(M.scrollForTime(0,pps,width,100),0);
    assert.equal(M.scrollForTime(100,pps,width,100),100*pps-(width-74));
  }
  assert.equal(M.scrollForTime(1,20,1280,2),0);
});
